config/routes.rb
Rails.application.routes.draw do
  resources :sections
    resources :rooms
  resources :area_types
  resources :sites
  devise_for :users, controllers: {
  registrations: "users/registrations"
  }

   resources :users do
    member do
      patch :toggle_access
       patch :toggle_status
    end
  end

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  post "/toggle_sign_ups", to: "settings#toggle_sign_ups", as: "toggle_sign_ups"
  
  get "home/index"
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sites, dependent: :destroy
  has_many :area_types, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :sections, dependent: :destroy
  has_many :area_types, dependent: :destroy

  
  has_one_attached :image

  validates :username, presence: true
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :validatable, :trackable, :timeout_in => 20.minutes

  def  self.online
    where("last_seen_at >= ?", 10.minutes.ago)
  end
  
   def online?
    last_seen_at && last_seen_at > 10.minutes.ago
  end
        
   # Example roles: admin, manager, staff, employee
  ROLES = %w[admin manager staff employee]

  def self.categories
    ROLES
  end

  def admin?
    role == 'admin'
  end

  def manager?
    role == "manager"
  end

  def staff?
    role == "staff"
  end

  def employee?
    role == "employee"
  end

  def can_access_data?
    access_granted?
  end

  def access_granted?
    admin? || self[:access_granted]
  end

  def active_for_authentication?
    super && status?
  end

  def inactive_message
    status? ? super : :account_inactive
  end  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_sign_up_enabled, only: [:new, :create]

def create
    build_resource(sign_up_params)

    if User.count.zero?
      resource.role = "admin"
      resource.access_granted = true
    else
      resource.role = "employee"
      resource.access_granted = false
    end

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

    private

  def check_sign_up_enabled
  return if User.count.zero? # Allow first user to sign up

  unless Setting.first&.sign_ups_enabled?
    flash[:alert] = "Sign ups are currently disabled."
    redirect_to root_path
  end
end

private

  def sign_up_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :image, :role, :access_granted, :sign_in_count)
  end

  def account_update_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :current_password, :image, :role, :access_granted)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :check_access
  
  def index
    @users = User.all
  end

  def edit
  end

  def show
     @user = User.find(params[:id])
  end

  def create
    user_count = User.count
    @user = User.new(user_params)
    @user.role = user_count.zero? ? "admin" : "employee"
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "User updated successfully."
    else
      render :edit, alert: "Failed to update user."
    end
  end

  def destroy
    if @user != current_user
      @user.destroy
      redirect_to users_path, notice: "User deleted."
    else
      redirect_to users_path, alert: "You cannot delete yourself."
    end
  end
  
  def check_access
    unless current_user&.access_granted?
      redirect_to root_path, alert: "You do not have access to this section."
    end
  end

  def toggle_status
  user = User.find(params[:id])

  # Prevent disabling the first created user
  if user == User.order(:created_at).first
    redirect_to users_path, alert: "You cannot change the status of the first admin user."
    return
  end

  user.update(status: !user.status)
  redirect_to users_path, notice: "User status updated."
end


  def toggle_access
  @user = User.find(params[:id])  # Finds the user by ID

  @user.update(access_granted: !@user.access_granted)  
  # Flips the current value of `access_granted`
  # If it was true, becomes false; if false, becomes true

  respond_to do |format|
    format.turbo_stream  # If using Turbo, this will stream an update to the view
    format.html { redirect_to users_path, notice: "Access updated." }  
    # Fallback: redirect with a flash notice
  end
end


  def check_admin
    redirect_to root_path, alert: "Admin access only." unless current_user&.admin?
  end

  private

  def require_admin
    redirect_to root_path, alert: "Not authorized." unless current_user.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :role) # adjust as needed
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_online_list.html.erb
<ul>
  <% online_users.each do |user| %>
    <li><%= user.username %> is online</li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<% content_for :title, "Users" %>

<div class="container">
<%= form_with(model: @user, local: true) do |f| %>
  <div class="mb-3">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="field">
  <%= f.label :role %>
    <% first_user = User.order(:created_at).first %>
    <%= f.select :role, User::ROLES, { prompt: "-Select Role-" }, { class: "form-control", disabled: (@user == first_user) } %>
  </div><br/>

  <div style="max-width: 25rem;">
    <%= f.label :image %>
    <%= f.file_field :image, class:"form-control" %>
  </div><br/>

  <%= f.submit "Update User", class: "btn btn-success btn-sm" %>
<% end %>
</div>

app/views/users/index.html.erb
<% content_for :title, "Users" %>

<div class="container">

<div>
<% setting = Setting.first_or_create(sign_ups_enabled: false) %>

<%= form_with url: toggle_sign_ups_path, method: :post, local: true do %>
  <%= submit_tag(setting.sign_ups_enabled? ? "Disable Sign Ups" : "Enable Sign Ups", 
                 class: "btn btn-#{setting.sign_ups_enabled? ? 'danger btn-sn' : 'success btn-sm'}") %>
<% end %>
</div>

<table class="table table-bordered table-striped sticky-header">
  <thead style="position: sticky; top: 0; background-color: rgb(146, 211, 232); z-index: 10;">
    <tr>
      <th>Id</th>
      <th>Email</th>
      <th>Name</th>
      <th>Status</th>
      <th>Role</th>
      <th>Actions</th>
      <th colspan="2">Online Status</th>
      <th>Sign In Count</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td>
          <%= form_with url: toggle_status_user_path(user), method: :patch, local: true do %>
            <%= hidden_field_tag :status, false %>
             <%= check_box_tag :status, true, user.status, onchange: 'this.form.submit();' %>
            <% end %>
        </td>
        <td><%= user.role %></td>
        <td>
          <%= link_to "Edit", edit_user_path(user), class: "btn btn-sm btn-warning btn-sm" %>
        <td>
           <% if user.online? %>
             <span class="badge bg-success">Online</span>
           <% else %>
             <span class="badge bg-secondary">Offline</span>
           <% end %>
        </td>
        <td>
          <% if user.last_seen_at.present? %>
            Last seen: <%= time_ago_in_words(user.last_seen_at) %> ago
          <% else %>
            Never logged in
          <% end %>
        </td> 
        <td>
          <p><%= user.username %> has logged in <%= user.sign_in_count %> times.</p>
        </td>    
       </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/users/show.html.erb
<% content_for :title, "user" %>

<div class="container">

<% if @user %>

<div class="card mb-3" style="max-width: 400px;">
  <div class="card-header bg-primary text-white">
    <%= @user.username %>
  </div>

  <div class="card-body">
    <p class="card-text">
      <strong>Email:</strong> <%= @user.email %><br>
      
    </p>
  </div>
</div>
 
<div>
  <%= link_to "Edit", edit_user_path(@user), class:"btn btn-warning btn-sm" %> |
  <%= link_to "Back", users_path, class:"btn btn-primary btn-sm" %> |
  <%= link_to "Delete", @user, method: :delete, data: { confirm: "Are you sure you want to delete this user?" }, class: "btn btn-danger btn-sm" %>
</div><br/>
</div>

<% else %>
  <p>User not found.</p>
<% end %>
</div>