config/routes.rb
Rails.application.routes.draw do
  resources :sections
    resources :rooms
  resources :area_types
  resources :sites
  devise_for :users, controllers: {
  registrations: "users/registrations"
  }

   resources :users do
    member do
      patch :toggle_access
       patch :toggle_status
    end
  end

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  post "/toggle_sign_ups", to: "settings#toggle_sign_ups", as: "toggle_sign_ups"
  
  get "home/index"
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<div class="mb-3">
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top no-print" style="background-color: rgb(146, 211, 232);">
    <div class="container-fluid">
      
      <div class="mb-0">
       <ul>
          <h2><i><%= link_to 'Nola Solutions', root_path, class:'navbar-brand', style: 'color: #006633;' %></i></h2>
       </ul>
      </div>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0"> 

        <% if current_user.admin? %>  
        <div class="input-group mb-0 me-1">
          <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-label="false">User Management</button>
            <ul class="dropdown-menu bg-light">
                <li><a class="dropdown-item" href="<%= users_path %>">Users</a></li>
            </ul>
        </div>
         <% end%>        

        <div class="input-group mb-0 me-1">
          <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Area Types</button>
            <ul class="dropdown-menu bg-light">
              <li><a class="dropdown-item" href="<%= area_types_path %>">View</a></li>
              <li><a class="dropdown-item" href="<%= new_area_type_path %>">New</a></li>
            </ul>
        </div>
        
        <div class="input-group mb-0 me-1">
          <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Sites</button>
            <ul class="dropdown-menu bg-light">
              <li><a class="dropdown-item" href="<%= sites_path %>">View</a></li>
              <li><a class="dropdown-item" href="<%= new_site_path %>">New</a></li>
            </ul>
        </div>
        
        <div class="input-group mb-0 me-1">
          <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Rooms</button>
            <ul class="dropdown-menu bg-light">
              <li><a class="dropdown-item" href="<%= rooms_path %>">View</a></li>
              <li><a class="dropdown-item" href="<%= new_room_path %>">New</a></li>
            </ul>
        </div>  
        
        <div class="input-group mb-0 me-1">
          <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Sections</button>
            <ul class="dropdown-menu bg-light">
              <li><a class="dropdown-item" href="<%= sections_path %>">View</a></li>
              <li><a class="dropdown-item" href="<%= new_section_path %>">New</a></li>
            </ul>
        </div>   
          
        <% if current_user.admin? %>
        <div>
          <% setting = Setting.first_or_create(sign_ups_enabled: false) %>

        <%= form_with url: toggle_sign_ups_path, method: :post, local: true do %>
          <%= submit_tag(setting.sign_ups_enabled? ? "Disable Sign Ups" : "Enable Sign Ups", 
                 class: "btn btn-#{setting.sign_ups_enabled? ? 'danger' : 'success'}") %>
        <% end %>
        </div>
        <% end %>
        
       </div> 
        <% if user_signed_in? %>
          <h5>Welcome <%= current_user.username %>!</h5>
        <% end %>
       </div>

       <div class="me-3">
         <% if current_user && current_user.image.attached? %>
            <%= image_tag url_for(current_user.image), class: "rounded-circle", size: "60x60" %>
         <% else %>
           <p>No image uploaded.</p>
         <% end %>
       </div>

        <form class="me-3">    
          <div class="input-group mb-0">
           <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">My Profile</button>
            <ul class="dropdown-menu bg-light">
                <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Edit Profile</a></li>
                <li><%= link_to "Sign Out", sign_out_path, class: "dropdown-item", data: { confirm: "Are you sure you want to sign out?" } %></li>
            </ul>
          </div> 
        </form>
  </nav>
  <% end %>
  </div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>