config/routes.rb
Rails.application.routes.draw do
  resources :sections
    resources :rooms
  resources :area_types
  resources :sites
  devise_for :users, controllers: {
  registrations: "users/registrations"
  }

   resources :users do
    member do
      patch :toggle_access
       patch :toggle_status
    end
  end

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  post "/toggle_sign_ups", to: "settings#toggle_sign_ups", as: "toggle_sign_ups"
  
  get "home/index"
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   
end

app/controllers/area_types_controller.rb
class AreaTypesController < ApplicationController
  before_action :set_area_type, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /area_types or /area_types.json
  def index
    @area_types = AreaType.all
  end

  # GET /area_types/1 or /area_types/1.json
  def show
  end

  # GET /area_types/new
  def new
    @area_type = AreaType.new
  end

  # GET /area_types/1/edit
  def edit
  end

  # POST /area_types or /area_types.json
  def create
    @area_type = AreaType.new(area_type_params)

    respond_to do |format|
      if @area_type.save
        format.html { redirect_to @area_type, notice: "Area type was successfully created." }
        format.json { render :show, status: :created, location: @area_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @area_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /area_types/1 or /area_types/1.json
  def update
    respond_to do |format|
      if @area_type.update(area_type_params)
        format.html { redirect_to @area_type, notice: "Area type was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @area_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @area_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /area_types/1 or /area_types/1.json
  def destroy
    @area_type.destroy!

    respond_to do |format|
      format.html { redirect_to area_types_path, notice: "Area type was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area_type
      @area_type = AreaType.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def area_type_params
      params.expect(area_type: [ :name, :user_id ])
    end
end

app/helpers/area_types_helper.rb
module AreaTypesHelper
end

app/views/area_types/_area_type.html.erb
<table class="table">
  <thead style="position: sticky; top: 0; background-color: rgb(146, 211, 232); z-index: 10;">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
   <% @area_types.each do |a|%>
    <tr>
      <td><%= a.id %></td>
      <td><%= a.name %></td>
      <td>
        <%= link_to "View", a, class:"btn btn-primary btn-sm" %> 
      </td>
    </tr>
   <% end %>
  </tbody>
</table>

app/views/area_types/_form.html.erb
<%= form_with(model: area_type) do |form| %>
  <% if area_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(area_type.errors.count, "error") %> prohibited this area_type from being saved:</h2>

      <ul>
        <% area_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <% if current_user %>
      <%= form.label :user_id, hidden: true %>
      <%= form.number_field :user_id, id: :area_type_user_id, class:"form-control", value: current_user.id, hidden: true %>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>


  <div>
    <%= form.submit nil, class:"btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/area_types/edit.html.erb
<% content_for :title, "Editing area type" %>

<h1>Editing area type</h1>

<%= render "form", area_type: @area_type %>

<br>

<div>
  <%= link_to "Back to area types", area_types_path, class:"btn btn-primary btn-sm" %>
</div>

app/views/area_types/index.html.erb
<% content_for :title, "Area types" %>

<div class="text-end mb-3">
  <%= link_to "New area type", new_area_type_path, class:"btn btn-success btn-sm" %>
</div

<div id="area_types">
 
    <%= render "area_types/area_type" %>
   
</div>

app/views/area_types/new.html.erb
<% content_for :title, "New area type" %>

<h1>New area type</h1>

<%= render "form", area_type: @area_type %>

<br>

<div>
  <%= link_to "Back to area types", area_types_path, class:"btn btn-primary btn-sm" %>
</div>

app/views/area_types/show.html.erb
<p>
  <strong>Area type:</strong>
  <%= @area_type.name %>
</p>

<p>
  <strong>Created By:</strong>
  <%= @area_type.user&.username %>
</p>

<div>
  <%= link_to "Edit this area tpye", edit_area_type_path(@area_type), class:"btn btn-warning btn-sm" %> |
  <%= link_to "Back to area type", area_types_path, class:"btn btn-primary btn-sm" %> |
  <%= link_to "Delete", @area_type, data: { turbo_method: "delete", turbo_confirm: "Are you sure?"}, class:"btn btn-danger btn-sm" %>
</div>